modLoader="javafml"
loaderVersion="[31,)"
license="TODO"

[[mods]]
modId="#ID#"
version="${file.jarVersion}"
displayName="#NAME#"

[[dependencies.#ID#]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.#ID#]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"

#FORGE_TOML_DEPENDENCIES#