name: Universal Mod Core CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                ref=`echo ${github_ref} | sed -e 's,refs/heads/,,' | tr '/' '-'`
                echo $ref
                echo "::set-env name=ref::$ref"
              env:
                github_ref: ${{ github.ref }}
            - name: Gradle build
              run: ./gradlew build
            - uses: actions/upload-artifact@v2-preview
              with:
                name: UniversalModCore-${{ env.ref }}
                path: build/libs/UniversalModCore-0.1.0-1.12.2-forge.jar
            - uses: actions/upload-artifact@v2-preview
              with:
                name: UniversalModCore-${{ env.ref }}-sources
                path: build/libs/UniversalModCore-0.1.0-1.12.2-forge-sources.jar


